"""Provider mutations: what may be written, on whose say-so, and how it is undone.

This is the first part of the runtime that can change a live financial account,
and it is built so that every step a person would want to audit afterwards
happened on purpose and left a record.

Four rules shape everything here.

**A decision is not an authorization.** `decide` records judgment and says so:
its action vocabulary has no write in it, and a recorded decision is a terminal
artifact for review. A mutation reads those records as *input* — the category to
set comes from the store, never from a proposal file — and then requires a
separate, explicit human authorization naming who is asking and why.

**Dry run is the default and describes the real request.** The rendering below
is produced from the same `PlannedMutation` objects `apply_plan` executes, and
names the endpoint, the transaction, the field, and both values. A preview
generated by different code from the thing it previews is a preview of nothing.

**The provider is re-read immediately before the write.** A plan is built from
the local snapshot, which is by definition a statement about the past. Between
planning and writing, a transaction can be recategorized in the app, deleted, or
replaced. Every one of those makes the plan wrong in a way only the provider
knows, so the live document is fetched, checked field by field against what was
planned, and refused if it moved.

**Only verified endpoints are callable.** The capability registry below carries
every mutation this project has considered, including the ones it will not
perform, with the reason. `transaction_category` is available because the
request shape, the job envelope and the polling endpoint were captured against
the live app. Rule writes are not, because no rule endpoint was ever observed
and the semantics of a contains-style match operator are unverified — see the
[API reference](../../references/simplifi-api.md).
"""

from __future__ import annotations

import copy
import json
import time
import uuid
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

#: Recorded verdict + action pair that makes a category write eligible. A
#: proposal is only ever a candidate; this is the reviewer having accepted it.
ELIGIBLE_DECISION = "accept"
ELIGIBLE_ACTION = "record_category_proposal"

#: Seconds between writes. The provider publishes a manual-refresh rate limit
#: but nothing about write rates, so this is deliberately conservative: a burst
#: that trips an undocumented limit fails partway through a batch, which is the
#: worst shape a batch of financial writes can fail in.
WRITE_INTERVAL_SECONDS = 1.0

#: How long to wait for a write job to settle, and how often to ask.
JOB_TIMEOUT_SECONDS = 30.0
JOB_POLL_SECONDS = 1.0

#: Job statuses that mean the provider finished the work.
JOB_SUCCESS_STATUSES = frozenset({"success", "succeeded", "complete", "completed", "done"})
JOB_FAILURE_STATUSES = frozenset({"failed", "failure", "error", "rejected", "cancelled"})

OUTCOME_SUCCEEDED = "succeeded"
OUTCOME_FAILED = "failed"
OUTCOME_UNKNOWN = "unknown"


class MutationError(RuntimeError):
    """A mutation could not be planned, authorized, or carried out."""


class AuthorizationError(MutationError):
    """The runtime was asked to write without an explicit human authorization."""


class PreconditionError(MutationError):
    """The world moved between planning and writing."""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


# --- capabilities -----------------------------------------------------------


@dataclass(frozen=True)
class MutationCapability:
    """One thing the runtime could do to a live account, and what it costs.

    Registered whether or not it is available. A capability that is refused for
    a reason nobody wrote down gets re-proposed every few months; one that
    carries its reason is a decision that stays decided.
    """

    name: str
    summary: str
    method: str
    path: str
    #: How the endpoint's behavior is known. Only `verified` may be called.
    evidence: str
    #: What this changes beyond the field named, and what it cannot undo.
    risk: str
    #: How far a mistake reaches: one transaction, one account, everything.
    blast_radius: str
    #: Whether the runtime can restore the prior state itself.
    reversible: bool
    available: bool
    #: Why not, when it is not.
    unavailable_because: str = ""


CAPABILITIES: dict[str, MutationCapability] = {
    "transaction_category": MutationCapability(
        name="transaction_category",
        summary="Set one transaction's category.",
        method="PUT",
        path="/transactions/{id}",
        evidence=(
            "Verified against the live web app on 2026-08-04/05: full-document PUT, "
            "job envelope response, settled via /job-statuses/{id}."
        ),
        risk=(
            "A full-document write. Every field in the request replaces the provider's "
            "copy, so a document assembled from anything other than the live one can "
            "silently revert edits made in the app since the last read. The category "
            "affects budgets, reports and any rule keyed on it, retroactively."
        ),
        blast_radius="one transaction",
        reversible=True,
        available=True,
    ),
    "transaction_rule": MutationCapability(
        name="transaction_rule",
        summary="Create or edit a renaming/categorization rule.",
        method="POST",
        path="/transaction-rules",
        evidence="Unverified — no rule endpoint was ever captured.",
        risk=(
            "A rule applies to every transaction that matches it, retroactively and "
            "going forward. Its blast radius is the match set, which cannot be "
            "predicted without knowing whether the match operator is whole-token or "
            "substring — and that is unverified too."
        ),
        blast_radius="every matching transaction, past and future",
        reversible=False,
        available=False,
        unavailable_because=(
            "The endpoint and the matching semantics are both unverified. ADR-005 "
            "requires a narrow term and a predicted match count before a rule write; "
            "neither can be produced against unknown matching. See the API reference, "
            "'Transaction rules and renaming'."
        ),
    ),
    "institution_refresh": MutationCapability(
        name="institution_refresh",
        summary="Trigger a bank refresh for one connection.",
        method="POST",
        path="/institution-logins/refresh",
        evidence="Verified shape; the in-band MFA channel was never exercised.",
        risk=(
            "Not a data write, but it consumes the provider's manual-refresh allowance "
            "and can present an institution MFA challenge that a scheduled run has no "
            "way to answer, leaving the connection in a challenged state."
        ),
        blast_radius="one institution connection",
        reversible=False,
        available=False,
        unavailable_because=(
            "Out of scope for this issue, which implements data mutations. A refresh "
            "capability needs its own interactive MFA path before it can be run at all, "
            "and none exists."
        ),
    ),
    "transaction_delete": MutationCapability(
        name="transaction_delete",
        summary="Delete a transaction.",
        method="DELETE",
        path="/transactions/{id}",
        evidence="Unverified — never captured.",
        risk="Destroys history the reconciler cannot rebuild from any local record.",
        blast_radius="one transaction, irrecoverably",
        reversible=False,
        available=False,
        unavailable_because=(
            "No deletion endpoint was captured, and nothing in the read-only workflow "
            "produces a finding whose remedy is deleting a transaction."
        ),
    ),
}


def capability(name: str) -> MutationCapability:
    """The named capability, or a refusal that says what was asked for."""
    found = CAPABILITIES.get(name)
    if found is None:
        raise MutationError(
            f"unknown mutation capability {name!r}; this runtime knows {sorted(CAPABILITIES)}"
        )
    if not found.available:
        raise MutationError(f"{name} is not available: {found.unavailable_because}")
    return found


# --- authorization ----------------------------------------------------------


@dataclass(frozen=True)
class Authorization:
    """A person, in their own words, saying to write to their account.

    Deliberately not a flag. `--yes` records that a boolean was true at some
    point, which is unauditable: nobody reading the trail later can tell an
    intentional approval from a flag left in a shell history or a cron line.
    """

    authorized_by: str
    note: str
    authorized_at: str = field(default_factory=_now)

    def __post_init__(self) -> None:
        if not str(self.authorized_by).strip():
            raise AuthorizationError("an authorization must name who is authorizing it")
        if len(str(self.note).strip()) < 12:
            raise AuthorizationError(
                "an authorization must say why, in a sentence; a word is not a reason"
            )


# --- planning ---------------------------------------------------------------


@dataclass(frozen=True)
class PlannedMutation:
    """One intended change, complete enough to preview, execute, and audit."""

    capability: MutationCapability
    transaction_id: str
    field_name: str
    before_value: str
    after_value: str
    decision_id: str
    run_id: int
    source: str
    source_hash: str
    #: The local row this was planned from, for the preview only. The document
    #: actually written is built from the provider's live copy.
    payee_display: str = ""
    posted_on: str = ""
    #: The decision-relevant facts as the reviewer saw them, keyed by the
    #: provider's own field names so the live document compares directly.
    reviewed_facts: Mapping[str, str] = field(default_factory=dict)

    def describe(self) -> str:
        """Exactly what would be sent, in one paragraph."""
        return (
            f"{self.capability.method} {self.capability.path.format(id=self.transaction_id)}\n"
            f"  transaction : {self.transaction_id}"
            f"{f' ({self.payee_display}, {self.posted_on})' if self.payee_display else ''}\n"
            f"  field       : {self.field_name}\n"
            f"  from        : {self.before_value or '(uncategorized)'}\n"
            f"  to          : {self.after_value}\n"
            f"  authority   : decision {self.decision_id} from run {self.run_id}\n"
            f"  reversible  : {'yes, by restoring the preserved document' if self.capability.reversible else 'no'}"
        )


def plan_category_writes(
    decisions: Sequence[Mapping[str, Any]],
    rows: Sequence[Mapping[str, Any]],
    *,
    latest_run_id: int,
    retired_transaction_ids: Iterable[str] = (),
    already_applied: Iterable[str] = (),
) -> tuple[list[PlannedMutation], list[str]]:
    """Turn accepted category decisions into a plan, and say what was skipped.

    Returns `(plan, skipped)`. Skips are returned rather than raised: a batch
    where one proposal went stale is the normal case, and refusing the whole
    batch would push an operator towards re-running until nothing is skipped —
    which is the opposite of what the staleness check is for.
    """
    by_id = {str(row.get("transaction_id")): row for row in rows}
    retired = {str(txid) for txid in retired_transaction_ids}
    applied = {str(decision_id) for decision_id in already_applied}
    cap = capability("transaction_category")

    # Decision records are append-only, so a transaction reviewed twice has two
    # of them and the later one is the reviewer's current judgment. Evaluating
    # each independently planned a superseded acceptance alongside its
    # replacement — writing a category the reviewer had already changed their
    # mind about, or two conflicting writes in sequence.
    newest: dict[str, Mapping[str, Any]] = {}
    superseded: list[str] = []
    for record in decisions:
        transaction_id = str(record.get("transaction_id") or "")
        previous = newest.get(transaction_id)
        if previous is not None:
            superseded.append(
                f"{previous.get('decision_id')}: superseded by "
                f"{record.get('decision_id')} for {transaction_id}"
            )
        newest[transaction_id] = record

    plan: list[PlannedMutation] = []
    skipped: list[str] = list(superseded)
    for record in newest.values():
        decision_id = str(record.get("decision_id") or "")
        transaction_id = str(record.get("transaction_id") or "")
        target = str(record.get("category") or "")

        if str(record.get("decision")) != ELIGIBLE_DECISION:
            continue
        if str(record.get("action")) != ELIGIBLE_ACTION:
            continue
        if not target:
            skipped.append(f"{decision_id}: accepted with no category to set")
            continue
        if decision_id in applied:
            skipped.append(f"{decision_id}: already applied by an earlier mutation")
            continue
        # A decision about a superseded run was judged against a different view
        # of the data. It may still be right, but nothing here can establish
        # that, and re-running `analyze` and re-reviewing is cheap.
        if int(record.get("run_id") or 0) != int(latest_run_id):
            skipped.append(
                f"{decision_id}: reviewed run {record.get('run_id')}, "
                f"but the latest successful run is {latest_run_id}"
            )
            continue
        if transaction_id in retired:
            skipped.append(f"{decision_id}: {transaction_id} has been retired since the review")
            continue
        row = by_id.get(transaction_id)
        if row is None:
            skipped.append(f"{decision_id}: {transaction_id} is not a current transaction")
            continue
        # The proposal named a starting category. If the row no longer holds it,
        # something changed the transaction after the review and the reviewer
        # was looking at a different fact.
        current = str(row.get("category") or "")
        if current == target:
            skipped.append(f"{decision_id}: {transaction_id} is already {target!r}")
            continue
        stored_hash = str(record.get("proposal_hash") or "")
        plan.append(
            PlannedMutation(
                capability=cap,
                transaction_id=transaction_id,
                field_name="coa (category)",
                before_value=current,
                after_value=target,
                decision_id=decision_id,
                run_id=int(record.get("run_id") or 0),
                source=str(record.get("source") or ""),
                source_hash=str(row.get("source_hash") or stored_hash),
                payee_display=str(row.get("payee_display") or ""),
                posted_on=str(row.get("posted_on") or ""),
                reviewed_facts=_facts_from_row(row),
            )
        )
    return plan, skipped


def render_plan(plan: Sequence[PlannedMutation], skipped: Sequence[str] = ()) -> str:
    """The dry-run text. Built from the plan `apply_plan` executes, not beside it."""
    lines = [f"{len(plan)} mutation(s) planned, {len(skipped)} skipped."]
    for index, planned in enumerate(plan, start=1):
        lines.append("")
        lines.append(f"[{index}] {planned.capability.summary}")
        lines.append(planned.describe())
    if skipped:
        lines.append("")
        lines.append("Skipped:")
        lines.extend(f"  - {reason}" for reason in skipped)
    if plan:
        lines.append("")
        lines.append(
            "Nothing has been sent. This is a description of the requests that would be "
            "made, produced from the same plan that would make them."
        )
    return "\n".join(lines)


# --- writing ----------------------------------------------------------------


class TransactionWriter:
    """What `apply_plan` needs from a provider, and nothing else.

    A narrow protocol so the tests can drive the whole path — preconditions,
    job polling, audit, undo — against a fixture that never opens a socket.
    Financial writes are not something to exercise against a real account in
    order to find out whether the code works.
    """

    def fetch(self, transaction_id: str) -> dict:  # pragma: no cover - interface
        raise NotImplementedError

    def category_id(self, name: str) -> str | None:  # pragma: no cover - interface
        """The provider's ID for a category display name, when resolvable."""
        return None

    def write(self, document: Mapping[str, Any]) -> dict:  # pragma: no cover - interface
        raise NotImplementedError

    def job_status(self, job_id: str) -> dict:  # pragma: no cover - interface
        raise NotImplementedError


@dataclass
class ApiTransactionWriter(TransactionWriter):
    """The verified `PUT /transactions/{id}` path, and its job polling."""

    client: Any

    def fetch(self, transaction_id: str) -> dict:
        return dict(self.client.get(f"/transactions/{transaction_id}"))

    def write(self, document: Mapping[str, Any]) -> dict:
        return dict(self.client.put(f"/transactions/{document['id']}", dict(document)))

    def job_status(self, job_id: str) -> dict:
        return dict(self.client.get(f"/job-statuses/{job_id}"))

    def category_id(self, name: str) -> str | None:
        """Resolve a category display name to the provider's ID.

        `GET /categories` is a verified read. Category resources carry `name`
        and `parentId` and no full path, so display paths are built by walking
        parents; matching here is on the leaf name, which is what a decision
        record carries.
        """
        wanted = name.split(":")[-1].strip().casefold()
        for resource in self.client.paged("/categories"):
            if str(resource.get("name", "")).strip().casefold() == wanted:
                return str(resource.get("id"))
        return None


def _category_of(document: Mapping[str, Any]) -> str:
    coa = document.get("coa")
    if isinstance(coa, Mapping):
        return str(coa.get("name") or coa.get("id") or "")
    return ""


def apply_category(
    document: Mapping[str, Any], category: str, category_id: str | None = None
) -> dict:
    """A deep copy of the live document with the category reference replaced.

    Deep, because `coa` is a nested object: a shallow copy would hand the same
    dictionary to both documents and the "before" payload written to the audit
    would silently acquire the new value — the audit would record that nothing
    changed, on the one write where knowing what changed is the entire point.

    The whole reference is replaced, not just its name. Spreading the existing
    `coa` and setting `name` kept the *old* `id` alongside the new label, and
    `coa.id` is what the read path resolves — so the document would have
    identified the old category under the new category's display name, and the
    provider could reasonably keep the old one or reject the object outright.
    """
    updated = copy.deepcopy(dict(document))
    coa = updated.get("coa")
    replacement: dict[str, Any] = {"name": category, "type": "CATEGORY"}
    if category_id is not None:
        replacement["id"] = category_id
    elif isinstance(coa, Mapping) and "id" in coa:
        # No resolved ID: drop the stale one rather than carry it. A document
        # naming the target category with the previous category's ID is a
        # contradiction; one with no ID is merely incomplete.
        pass
    updated["coa"] = replacement
    return updated


def _settle(
    writer: TransactionWriter, response: Mapping[str, Any], *, sleep=time.sleep
) -> tuple[str, str, str]:
    """Poll a write job until it settles. Returns `(outcome, job_id, status)`.

    A PUT returns a job envelope, not the updated transaction, so a 200 means
    the provider accepted the request — not that it did the work. Recording
    success there would put "category changed" in the audit for a job that went
    on to fail.
    """
    job_id = str(response.get("id") or "")
    status = str(response.get("status") or "")
    if not job_id:
        # No job to poll. The write was accepted and there is no way to confirm
        # it settled, which is `unknown` rather than success.
        return (
            (OUTCOME_SUCCEEDED if status.lower() in JOB_SUCCESS_STATUSES else OUTCOME_UNKNOWN),
            "",
            status,
        )
    deadline = time.monotonic() + JOB_TIMEOUT_SECONDS
    while True:
        if status.lower() in JOB_SUCCESS_STATUSES:
            return OUTCOME_SUCCEEDED, job_id, status
        if status.lower() in JOB_FAILURE_STATUSES:
            return OUTCOME_FAILED, job_id, status
        if time.monotonic() >= deadline:
            return OUTCOME_UNKNOWN, job_id, status
        sleep(JOB_POLL_SECONDS)
        try:
            status = str(writer.job_status(job_id).get("status") or "")
        except Exception:
            # A poll that fails says nothing about the job, which is still
            # running somewhere with an ID we know. Losing that ID would leave
            # the audit describing an unknown write the operator cannot look
            # up — and the decision is deliberately not retryable afterwards,
            # so the ID is the only handle left.
            return OUTCOME_UNKNOWN, job_id, status


def _classify_write_failure(exc: BaseException) -> str:
    """`failed` when the provider rejected it, `unknown` when nobody knows.

    `applied_decision_ids` treats anything that is not `failed` as applied and
    refuses to retry it, which is right for an ambiguous write and wrong for a
    rejected one: a token that expired mid-batch, or a payload the provider
    validated and refused, changed nothing, and the operator must be able to
    fix it and run again.

    A 5xx stays `unknown`. The request reached the provider, and a server error
    is not a statement that the work was not done.
    """
    from .sources.api_source import ApiError, TransportError

    if isinstance(exc, TransportError):
        return OUTCOME_UNKNOWN
    if isinstance(exc, ApiError):
        status = getattr(exc, "status_code", None)
        if isinstance(status, int) and 400 <= status < 500:
            return OUTCOME_FAILED
    return OUTCOME_UNKNOWN


@dataclass
class MutationResult:
    """What happened to one planned mutation."""

    attempt_id: str
    planned: PlannedMutation
    outcome: str
    job_id: str = ""
    job_status: str = ""
    error_class: str = ""
    error_message: str = ""

    @property
    def succeeded(self) -> bool:
        return self.outcome == OUTCOME_SUCCEEDED


#: Fields a reviewer's judgment rests on, under the provider's own names. A
#: pending charge that settles at a different amount is the ordinary case, and
#: it keeps its ID and its category throughout — so the category check alone
#: cannot see it.
REVIEWED_FACTS = ("amount", "payee", "postedOn", "state")

#: How a stored row spells the same facts.
_ROW_FIELD_FOR = {
    "amount": "amount_minor_units",
    "payee": "payee_raw",
    "postedOn": "posted_on",
    "state": "txn_state",
}


def _facts_from_document(document: Mapping[str, Any]) -> dict[str, str]:
    return {name: str(document.get(name, "")) for name in REVIEWED_FACTS}


def _facts_from_row(row: Mapping[str, Any]) -> dict[str, str]:
    """The reviewed facts as the local row records them.

    Compared as strings against the live document. If the provider's amount
    scaling ever differs from the stored minor units this refuses the write
    rather than performing it — the fail-safe direction, and a refusal is
    visible immediately where a wrong write is not.

    A fact the row never recorded is omitted rather than compared as empty: a
    CSV export carries no settlement state at all, and refusing every write
    over a column the source does not populate would be a check that only ever
    fires on the wrong thing.
    """
    facts = {}
    for name, column in _ROW_FIELD_FOR.items():
        value = row.get(column)
        if value is not None and str(value) != "":
            facts[name] = str(value)
    return facts


def _check_live_document(
    planned: PlannedMutation, live: Mapping[str, Any], reviewed: Mapping[str, str] | None = None
) -> None:
    """Refuse a write whose target moved since the plan was made."""
    if reviewed:
        moved = [
            name
            for name, value in _facts_from_document(live).items()
            if str(reviewed.get(name, value)) != value
        ]
        if moved:
            raise PreconditionError(
                f"{planned.transaction_id} changed since it was reviewed "
                f"({', '.join(moved)}); the reviewer approved a different transaction. "
                "Re-run `analyze` and review again"
            )
    live_category = _category_of(live)
    if live_category == planned.after_value:
        raise PreconditionError(
            f"{planned.transaction_id} is already {planned.after_value!r} at the provider; "
            "nothing to change"
        )
    if live_category != planned.before_value:
        raise PreconditionError(
            f"{planned.transaction_id} was {planned.before_value!r} when this was planned and "
            f"is {live_category!r} at the provider now; re-run `analyze` and review again"
        )
    if str(live.get("id") or "") != planned.transaction_id:
        raise PreconditionError(
            f"the provider returned transaction {live.get('id')!r} for {planned.transaction_id!r}"
        )


def apply_plan(
    store: Any,
    plan: Sequence[PlannedMutation],
    writer: TransactionWriter,
    authorization: Authorization,
    *,
    sleep: Callable[[float], None] = time.sleep,
    interval: float = WRITE_INTERVAL_SECONDS,
) -> list[MutationResult]:
    """Carry out a plan, one write at a time, recording every attempt.

    The attempt row is committed *before* the request leaves. A process killed
    mid-write then leaves an attempt with no outcome, which is the truth; a row
    written afterwards would leave nothing at all.
    """
    if not isinstance(authorization, Authorization):
        raise AuthorizationError("mutations require an explicit Authorization")

    results: list[MutationResult] = []
    for index, planned in enumerate(plan):
        if index and interval:
            sleep(interval)
        attempt_id = uuid.uuid4().hex

        try:
            live = writer.fetch(planned.transaction_id)
            _check_live_document(planned, live, planned.reviewed_facts)
        except PreconditionError as exc:
            # Nothing was sent, so there is no attempt to record — but the
            # refusal is the operator's answer, so it comes back as a result.
            results.append(
                MutationResult(
                    attempt_id=attempt_id,
                    planned=planned,
                    outcome=OUTCOME_FAILED,
                    error_class="PreconditionError",
                    error_message=str(exc),
                )
            )
            continue
        except Exception as exc:
            results.append(
                MutationResult(
                    attempt_id=attempt_id,
                    planned=planned,
                    outcome=OUTCOME_FAILED,
                    error_class=type(exc).__name__,
                    error_message=str(exc),
                )
            )
            continue

        try:
            resolved_id = writer.category_id(planned.after_value)
        except Exception as exc:
            results.append(
                MutationResult(
                    attempt_id=attempt_id,
                    planned=planned,
                    outcome=OUTCOME_FAILED,
                    error_class=type(exc).__name__,
                    error_message=f"could not resolve category {planned.after_value!r}: {exc}",
                )
            )
            continue
        if resolved_id is None:
            results.append(
                MutationResult(
                    attempt_id=attempt_id,
                    planned=planned,
                    outcome=OUTCOME_FAILED,
                    error_class="PreconditionError",
                    error_message=(
                        f"the provider has no category named {planned.after_value!r}; "
                        "this runtime cannot create one"
                    ),
                )
            )
            continue
        after = apply_category(live, planned.after_value, resolved_id)
        store.record_mutation_attempt(
            attempt_id=attempt_id,
            capability=planned.capability.name,
            transaction_id=planned.transaction_id,
            decision_id=planned.decision_id,
            run_id=planned.run_id,
            source=planned.source,
            source_hash=planned.source_hash,
            authorization=authorization,
            before_document=live,
            after_document=after,
            change_summary=(
                f"{planned.field_name}: {planned.before_value or '(uncategorized)'} "
                f"-> {planned.after_value}"
            ),
        )
        store.commit()

        try:
            response = writer.write(after)
            outcome, job_id, status = _settle(writer, response, sleep=sleep)
            error_class = error_message = ""
        except Exception as exc:
            outcome, job_id, status = _classify_write_failure(exc), "", ""
            error_class, error_message = type(exc).__name__, str(exc)

        store.record_mutation_outcome(
            attempt_id=attempt_id,
            outcome=outcome,
            job_id=job_id,
            job_status=status,
            error_class=error_class,
            error_message=error_message,
        )
        store.commit()
        results.append(
            MutationResult(
                attempt_id=attempt_id,
                planned=planned,
                outcome=outcome,
                job_id=job_id,
                job_status=status,
                error_class=error_class,
                error_message=error_message,
            )
        )
    return results


# --- undo -------------------------------------------------------------------


def undo(
    store: Any,
    attempt_id: str,
    writer: TransactionWriter,
    authorization: Authorization,
    *,
    sleep: Callable[[float], None] = time.sleep,
) -> MutationResult:
    """Restore the document preserved before a successful mutation.

    An undo is a new mutation, not an erasure: it appends its own attempt,
    points at the one it reverses, and can itself fail. Nothing about the
    original row changes, because the original write really did happen.

    It is a restore, not a rollback. The document written back is the one the
    provider served immediately before the change, so any *other* edit made in
    the app since then is overwritten too — that is what a full-document API
    makes possible and it is stated rather than hidden. The live document is
    checked first: if the field no longer holds what this mutation set, someone
    else changed it and the undo refuses rather than reverting their work.
    """
    if not isinstance(authorization, Authorization):
        raise AuthorizationError("an undo requires an explicit Authorization")

    original = store.mutation_attempt(attempt_id)
    if original is None:
        raise MutationError(f"no mutation attempt {attempt_id!r} in this database")
    outcome = store.mutation_outcome(attempt_id)
    if outcome is None or str(outcome.get("outcome")) != OUTCOME_SUCCEEDED:
        state = "never settled" if outcome is None else str(outcome.get("outcome"))
        raise MutationError(
            f"mutation {attempt_id} {state}; only a settled successful write can be undone. "
            "Check the provider directly before writing again."
        )
    existing = store.undo_of(attempt_id)
    if existing is not None:
        # An undo the provider definitively rejected changed nothing, so the
        # original still stands and still needs a way back. Only a settled
        # success, or an undo whose fate is unknown, blocks a retry — retrying
        # over an ambiguous one risks restoring twice.
        existing_outcome = store.mutation_outcome(str(existing["attempt_id"]))
        blocking = existing_outcome is None or str(existing_outcome["outcome"]) != OUTCOME_FAILED
        if blocking:
            raise MutationError(f"mutation {attempt_id} has already been undone")

    before = json.loads(str(original["before_document"]))
    after = json.loads(str(original["after_document"]))
    transaction_id = str(original["transaction_id"])

    live = writer.fetch(transaction_id)
    if _category_of(live) != _category_of(after):
        raise PreconditionError(
            f"{transaction_id} is {_category_of(live)!r} at the provider, not the "
            f"{_category_of(after)!r} this mutation set. Someone else changed it; "
            "undoing would overwrite their change"
        )

    undo_attempt_id = uuid.uuid4().hex
    restored = apply_category(
        live,
        _category_of(before),
        (before.get("coa") or {}).get("id") if isinstance(before.get("coa"), Mapping) else None,
    )
    store.record_mutation_attempt(
        attempt_id=undo_attempt_id,
        capability=str(original["capability"]),
        transaction_id=transaction_id,
        decision_id=original["decision_id"],
        run_id=original["run_id"],
        source=str(original["source"]),
        source_hash=str(original["source_hash"]),
        authorization=authorization,
        before_document=live,
        after_document=restored,
        change_summary=f"undo of {attempt_id}: restored {_category_of(before) or '(uncategorized)'}",
        undoes_attempt_id=attempt_id,
    )
    store.commit()

    try:
        response = writer.write(restored)
        result_outcome, job_id, status = _settle(writer, response, sleep=sleep)
        error_class = error_message = ""
    except Exception as exc:
        result_outcome, job_id, status = _classify_write_failure(exc), "", ""
        error_class, error_message = type(exc).__name__, str(exc)

    store.record_mutation_outcome(
        attempt_id=undo_attempt_id,
        outcome=result_outcome,
        job_id=job_id,
        job_status=status,
        error_class=error_class,
        error_message=error_message,
    )
    store.commit()
    planned = PlannedMutation(
        capability=CAPABILITIES[str(original["capability"])],
        transaction_id=transaction_id,
        field_name="coa (category)",
        before_value=_category_of(after),
        after_value=_category_of(before),
        decision_id=str(original["decision_id"] or ""),
        run_id=int(original["run_id"] or 0),
        source=str(original["source"]),
        source_hash=str(original["source_hash"]),
    )
    return MutationResult(
        attempt_id=undo_attempt_id,
        planned=planned,
        outcome=result_outcome,
        job_id=job_id,
        job_status=status,
        error_class=error_class,
        error_message=error_message,
    )


def describe_capabilities() -> str:
    """The capability and risk register, for `mutate --capabilities`."""
    lines = []
    for name in sorted(CAPABILITIES):
        cap = CAPABILITIES[name]
        lines.append(f"{name}  [{'available' if cap.available else 'UNAVAILABLE'}]")
        lines.append(f"  {cap.summary}")
        lines.append(f"  endpoint     : {cap.method} {cap.path}")
        lines.append(f"  evidence     : {cap.evidence}")
        lines.append(f"  risk         : {cap.risk}")
        lines.append(f"  blast radius : {cap.blast_radius}")
        lines.append(f"  reversible   : {'yes' if cap.reversible else 'no'}")
        if not cap.available:
            lines.append(f"  refused      : {cap.unavailable_because}")
        lines.append("")
    return "\n".join(lines).rstrip()


__all__ = [
    "CAPABILITIES",
    "ApiTransactionWriter",
    "Authorization",
    "AuthorizationError",
    "MutationCapability",
    "MutationError",
    "MutationResult",
    "PlannedMutation",
    "PreconditionError",
    "TransactionWriter",
    "apply_plan",
    "capability",
    "describe_capabilities",
    "plan_category_writes",
    "render_plan",
    "undo",
]
